//! Turn shared-root `.md` memory files into agent-consumable SKILL.md units.
//!
//! Each memory file becomes one skill named `memory-<kebab-slug>`. The prefix
//! is a load-bearing marker: `sync::sync_tool` uses it to identify stale
//! memory-derived skills that should be swept away when a memory file is
//! removed from the shared root. Do not change it without updating the sweep.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

pub const MEMORY_SKILL_PREFIX: &str = "memory-";

/// Marker line of the generated banner comment. A source file containing this
/// block has been fed through the generator before (agent write-backs can copy
/// a generated SKILL.md back into the shared root); the block must never
/// accumulate, so it is stripped before every generation.
const BANNER_START: &str = "<!-- Auto-generated by skills-manager memory module.";
/// Generated per-file header line that always follows a banner block.
const MEMORY_TYPE_LINE_PREFIX: &str = "**Memory type**:";

/// A single memory file rendered as a deploy-ready skill.
#[derive(Debug, Clone, Serialize)]
pub struct MaterializedMemory {
    pub slug: String,
    pub skill_name: String,
    pub description: String,
    pub source_path: String,
    pub memory_type: String,
    #[serde(skip_serializing)]
    pub skill_body: String,
}

#[derive(Debug, Deserialize)]
struct MemoryFrontmatter {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    metadata: Option<serde_yaml::Value>,
}

impl MemoryFrontmatter {
    /// Frontmatter written by a previous generation pass, not by a human.
    /// (Kept for structured parses; the reliable check in `materialize_one`
    /// runs on the raw frontmatter text because the generated description is
    /// deliberately informative-but-invalid YAML.)
    fn is_generated(&self) -> bool {
        self.name
            .as_deref()
            .map(|n| n.starts_with(MEMORY_SKILL_PREFIX))
            .unwrap_or(false)
            && self
                .description
                .as_deref()
                .map(|d| d.starts_with("[memory]"))
                .unwrap_or(false)
    }
}

/// Scan the shared root and materialize every eligible memory file.
///
/// Skipped: files under nested dirs, dotfiles, and `MEMORY.md` (an index).
/// When `heal` is set, a source that still carries generated artifacts
/// (banner blocks, a generated frontmatter) is rewritten in place to its
/// canonical clean form, so repeated syncs cannot grow it.
pub fn scan_and_materialize(root: &Path, heal: bool) -> Result<Vec<MaterializedMemory>> {
    if !root.exists() {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    for entry in fs::read_dir(root).with_context(|| format!("read_dir {}", root.display()))? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let filename = match path.file_name().and_then(|s| s.to_str()) {
            Some(n) => n,
            None => continue,
        };
        if filename == "MEMORY.md" || filename.starts_with('.') {
            continue;
        }
        match materialize_one(&path, heal) {
            Ok(m) => out.push(m),
            Err(err) => {
                log::warn!("memory materializer: skipping {}: {}", path.display(), err);
            }
        }
    }
    out.sort_by(|a, b| a.slug.cmp(&b.slug));
    Ok(out)
}

fn materialize_one(path: &Path, heal: bool) -> Result<MaterializedMemory> {
    let raw = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let (frontmatter_yaml, body) = split_frontmatter(&raw);
    let fm: MemoryFrontmatter = if frontmatter_yaml.is_empty() {
        MemoryFrontmatter {
            name: None,
            description: None,
            metadata: None,
        }
    } else {
        serde_yaml::from_str(frontmatter_yaml).unwrap_or(MemoryFrontmatter {
            name: None,
            description: None,
            metadata: None,
        })
    };
    let fm_generated = frontmatter_yaml.contains(&format!("name: {}", MEMORY_SKILL_PREFIX))
        && frontmatter_yaml.contains("description: [memory]");

    // A source that went through the generator (or a write-back of a
    // generated SKILL.md) carries banner blocks and a `**Memory type**` line
    // in its body. Strip them before regenerating, or every round would grow
    // the file by one banner — the failure mode behind WorkBuddy heap blowups
    // (files reaching ~2.7MB, banner repeated 10k+ times).
    //
    // The generated description `[memory] …` is not even valid YAML (it parses
    // as a flow sequence and then fails), so the generated check above runs on
    // the raw frontmatter text rather than on the parsed struct: when parsing
    // fails, `fm` falls back to all-None and the struct-based check would
    // never fire.
    let mut clean_body = strip_generated_blocks(body);
    if !fm_generated {
        clean_body = body.to_string();
    }

    if heal && (fm_generated || clean_body != body) {
        let healed = render_canonical_source(&clean_body);
        if healed != raw {
            atomic_write(path, healed.as_bytes()).with_context(|| {
                format!("heal generated artifacts in {}", path.display())
            })?;
            log::info!(
                "memory materializer: healed generated artifacts in {}",
                path.display()
            );
        }
    }

    let effective_fm = if fm_generated {
        MemoryFrontmatter {
            name: None,
            description: None,
            metadata: None,
        }
    } else {
        fm
    };
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown")
        .to_string();
    let slug_source = effective_fm.name.clone().unwrap_or_else(|| stem.clone());
    let slug = kebab_case(&slug_source);
    let skill_name = format!("{}{}", MEMORY_SKILL_PREFIX, slug);
    let description_original = effective_fm
        .description
        .clone()
        .unwrap_or_else(|| format!("Personal memory: {}", slug));
    let description = format!("[memory] {}", description_original);
    let memory_type = effective_fm
        .metadata
        .as_ref()
        .and_then(|m| m.get("type"))
        .and_then(|v| v.as_str())
        .unwrap_or("unspecified")
        .to_string();

    let skill_body = build_skill_body(&skill_name, &description, &memory_type, &clean_body, path);
    Ok(MaterializedMemory {
        slug,
        skill_name,
        description,
        source_path: path.to_string_lossy().to_string(),
        memory_type,
        skill_body,
    })
}

/// Remove generated banner comment blocks (and the `**Memory type**` line that
/// follows each of them) from a body, collapsing the leftover blank runs.
fn strip_generated_blocks(body: &str) -> String {
    if !body.contains(BANNER_START) {
        return body.to_string();
    }
    let mut out: Vec<&str> = Vec::new();
    let mut skipping_banner = false;
    let mut skip_next_type_line = false;
    for line in body.lines() {
        let trimmed = line.trim_start();
        if skipping_banner {
            if trimmed.contains("-->") {
                skipping_banner = false;
                skip_next_type_line = true;
            }
            continue;
        }
        if trimmed.starts_with(BANNER_START) {
            skipping_banner = true;
            continue;
        }
        if skip_next_type_line {
            if trimmed.starts_with(MEMORY_TYPE_LINE_PREFIX) {
                skip_next_type_line = false;
                continue;
            }
            if trimmed.is_empty() {
                continue;
            }
            skip_next_type_line = false;
        }
        out.push(line);
    }
    collapse_blank_runs(&out.join("\n"))
}

/// Collapse runs of 3+ newlines (blank-line runs beyond one blank line) left
/// behind by stripped blocks.
fn collapse_blank_runs(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut blanks = 0usize;
    for line in s.lines() {
        if line.trim().is_empty() {
            blanks += 1;
            if blanks > 1 {
                continue;
            }
        } else {
            blanks = 0;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Canonical on-disk form of a memory source: plain body, no generated
/// artifacts, single trailing newline.
fn render_canonical_source(body: &str) -> String {
    let trimmed = body.trim();
    if trimmed.is_empty() {
        String::new()
    } else {
        format!("{}\n", trimmed)
    }
}

pub(crate) fn atomic_write(destination: &Path, bytes: &[u8]) -> Result<()> {
    let temp = destination.with_extension(format!(
        "tmp.{}",
        std::process::id()
    ));
    fs::write(&temp, bytes)?;
    if destination.exists() {
        fs::remove_file(destination)?;
    }
    fs::rename(temp, destination)?;
    Ok(())
}

/// Split a Markdown file into (frontmatter YAML, body). Empty YAML if no fence.
fn split_frontmatter(raw: &str) -> (&str, &str) {
    for prefix in ["---\n", "---\r\n"] {
        if let Some(rest) = raw.strip_prefix(prefix) {
            for terminator in ["\n---\n", "\n---\r\n", "\r\n---\r\n", "\r\n---\n"] {
                if let Some(end_idx) = rest.find(terminator) {
                    let front = &rest[..end_idx];
                    let body_start = end_idx + terminator.len();
                    return (front, &rest[body_start..]);
                }
            }
        }
    }
    ("", raw)
}

pub(crate) fn kebab_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_was_sep = true;
    for c in s.chars() {
        if c.is_alphanumeric() {
            for lc in c.to_lowercase() {
                out.push(lc);
            }
            last_was_sep = false;
        } else if !last_was_sep {
            out.push('-');
            last_was_sep = true;
        }
    }
    let trimmed = out.trim_matches('-');
    if trimmed.is_empty() {
        "memory".to_string()
    } else {
        trimmed.to_string()
    }
}

fn build_skill_body(
    skill_name: &str,
    description: &str,
    memory_type: &str,
    body: &str,
    source_path: &Path,
) -> String {
    format!(
        "---\nname: {name}\ndescription: {desc}\n---\n\n<!-- Auto-generated by skills-manager memory module.\n     Source: {src}\n     Do not edit here — edit the source and run `skills-manager-cli memory sync`. -->\n\n**Memory type**: {mtype}\n\n{body}\n",
        name = skill_name,
        desc = description,
        src = source_path.display(),
        mtype = memory_type,
        body = body.trim(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use tempfile::tempdir;

    fn banner_block(source: &str) -> String {
        format!(
            "<!-- Auto-generated by skills-manager memory module.\n     Source: {}\n     Do not edit here — edit the source and run `skills-manager-cli memory sync`. -->\n\n**Memory type**: unspecified\n\n",
            source
        )
    }

    fn write_source(dir: &Path, name: &str, content: &str) -> PathBuf {
        let path = dir.join(name);
        fs::write(&path, content).unwrap();
        path
    }

    fn count_banners(s: &str) -> usize {
        s.matches(BANNER_START).count()
    }

    #[test]
    fn plain_source_materializes_once_and_stays_untouched() {
        let tmp = tempdir().unwrap();
        let path = write_source(tmp.path(), "user_contact.md", "call dad every sunday\n");

        let first = materialize_one(&path, false).unwrap();
        assert_eq!(count_banners(&first.skill_body), 1);
        // Nothing to heal in a clean source: the file must not be rewritten.
        let before = fs::read(&path).unwrap();
        materialize_one(&path, true).unwrap();
        assert_eq!(fs::read(&path).unwrap(), before);
    }

    #[test]
    fn bloated_generated_source_is_healed_to_canonical_form() {
        let tmp = tempdir().unwrap();
        let source = tmp.path().join("user_contact.md");
        let banner = banner_block(r"C:\Users\x\.agent-memory\user_contact.md");
        let bloated = format!(
            "---\nname: memory-user-contact\ndescription: [memory] Personal memory: user-contact\n---\n\n{banner}{banner}{banner}- dws contact user get-self\n"
        );
        fs::write(&source, &bloated).unwrap();

        let m = materialize_one(&source, true).unwrap();
        // The generated frontmatter is stripped, so identity falls back to the
        // stem: memory-user-contact, not memory-memory-user-contact.
        assert_eq!(m.skill_name, "memory-user-contact");
        // Exactly one banner comes from THIS generation, none inherited.
        assert_eq!(count_banners(&m.skill_body), 1);
        assert!(m.skill_body.contains("- dws contact user get-self"));

        // The source on disk was rewritten to its canonical clean form.
        let healed = fs::read_to_string(&source).unwrap();
        assert_eq!(count_banners(&healed), 0);
        assert!(healed.contains("- dws contact user get-self"));
        assert!(!healed.starts_with("---"));
    }

    #[test]
    fn repeated_sync_rounds_keep_bytes_and_banner_count_constant() {
        // Worst-case feedback: the deployed SKILL.md (generated output) is
        // written back into the shared root as the next source. Acceptance
        // criterion from the WorkBuddy incident report: 100 rounds must not
        // change the byte size or the banner count.
        let tmp = tempdir().unwrap();
        let root = tmp.path().join("agent-memory");
        fs::create_dir_all(&root).unwrap();
        write_source(&root, "user_contact.md", "call dad every sunday\n");

        let deployed = tmp.path().join("skills").join("memory-user-contact");
        fs::create_dir_all(&deployed).unwrap();
        let deployed_path = deployed.join("SKILL.md");

        let mut last_size = 0usize;
        let mut last_banners = 0usize;
        for round in 0..100 {
            let memories = scan_and_materialize(&root, true).unwrap();
            assert_eq!(memories.len(), 1);
            fs::write(&deployed_path, memories[0].skill_body.as_bytes()).unwrap();

            // Simulate the external write-back: the deployed copy becomes the
            // next round's source.
            if round == 50 {
                let out = fs::read_to_string(&deployed_path).unwrap();
                fs::write(root.join("user_contact.md"), &out).unwrap();
            }

            let size = fs::read(&deployed_path).unwrap().len();
            let banners = count_banners(&fs::read_to_string(&deployed_path).unwrap());
            if round > 0 {
                assert_eq!(size, last_size, "byte drift at round {round}");
                assert_eq!(banners, last_banners, "banner drift at round {round}");
            }
            assert_eq!(banners, 1);
            last_size = size;
            last_banners = banners;
        }
    }

    #[test]
    fn human_frontmatter_is_never_stripped_or_healed() {
        let tmp = tempdir().unwrap();
        let raw = "---\nname: my-note\ndescription: personal\nmetadata:\n  type: reference\n---\n\nkeep me\n";
        let path = write_source(tmp.path(), "my-note.md", raw);

        let m = materialize_one(&path, true).unwrap();
        assert_eq!(m.slug, "my-note");
        assert_eq!(m.memory_type, "reference");
        // Human content is not "healed" away.
        assert_eq!(fs::read_to_string(&path).unwrap(), raw);
        assert!(!m.skill_body.contains("keep me") == false);
    }

    #[test]
    fn body_comments_untouched_when_no_generated_banner_present() {
        let tmp = tempdir().unwrap();
        let raw = "intro\n\n<!-- some other tool's comment -->\n\n**Memory type**: custom\n\noutro\n";
        let path = write_source(tmp.path(), "mixed.md", raw);
        let m = materialize_one(&path, true).unwrap();
        assert!(m.skill_body.contains("some other tool's comment"));
        assert!(m.skill_body.contains("**Memory type**: custom"));
        assert!(m.skill_body.contains("intro") && m.skill_body.contains("outro"));
    }
}
